vich_uploader:
    db_driver: orm
    mappings:
        dest_image:
            uri_prefix: /images/destination
            upload_destination: '%kernel.project_dir%/public/images/destination'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        ville_image:
            uri_prefix: /images/villes
            upload_destination: '%kernel.project_dir%/public/images/villes'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
